### ISSUE TITLE
Alignment between references fail

### ISSUE THREAD

**Issue by ctparson** [jkimlab/RBRC#2]
I keep getting the following error message despite the references being two high quality genomes from NCBI.  Any suggestions for how to fix greatly appreciated: 
PARAMS check
readline() on closed filehandle PARAM at /RBRC/RBRC.pl line 58.
 Read id converting | working at /rbrc_wd/output/Reads
 - done

 Reference ID converting & weight calculation | working at /rbrc_wd/output/pre-processing
  Read mapping
 - done

 Whole genome alignment
 - done

 Building synteny blocks | working at /rbrc_wd/output/SynBased_clustering/synteny_blocks
Alignment between references was failed.
Please check the alignment files in /rbrc_wd/output/chainNet and change the set of references.

**Comment by jkimlab** [comment]
Thanks a lot for your interest in RBRC.
Can I see your params.txt file? 
And could you show me the command line you used?

**Comment by ctparson** [comment]
The command line used was : 
sudo docker run -v /LOCALDISK/reference:/rbrc_wd/reference -v /LOCALDISK/read:/rbrc_wd/read -v /LOCALDISK/output:rbrc_wd/output -t rbrc:latest RBRC.pl -p /rbrc_wd/output/params.txt -o /rbrc_wd/output

The params.txt contents are below.  Thanks in advance for your assistance

 #---------------------------------------------------------------------------------------#
  ## Mendatory !
  # Reference genomes
  REF	1	CB6318 /home/RBRC/References/C.parapsilosis_CB6318.fna
  REF	2	GA1.1 /home/RBRC/References/GCA_000982675.1_GA1.1_genomic.fna

  # NGS reads
  # FASTQ
  >LIB1
  /home/Sample/42090-1/42090_S2_L001_R1_001.fastq
  /home/Sample/42090-1/42090_S2_L001_R2_001.fastq

  #---------------------------------------------------------------------------------------#
  ## Optional
  # Running paramters
  THREADS        32
  REF_SIMILARITY_CUTOFF 80
  MAPQ 0

  # Pairwise alignment & synteny block construction params
  RESOLUTION	10000

  # Physical coverage paramters
  PHY_CUTOFF	LIB1	5

  # Distance based clustering paramters
  DBC_READ_DIST_CUTOFF	1000

  # Cluster merging parameter
  MERGE_MIN_READS	5
  #---------------------------------------------------------------------------------------#

**Comment by yotsa** [comment]
Hi,

I've got the exact same error. I still can't figure this out. 

The params.txt file was almost the same as above, and the running command is also almost the same with different directories in the volume mount:

docker run --rm=True -v /LOCALDISK/reference:/RUN/reference -v /LOCALDISK/read:/RUN/read/ -v /LOCALDISK/output:/RUN/output -t jkimlab/rbrc:latest RBRC.pl -p /RUN/output/params.txt -o /RUN/output

Yot

**Comment by jkimlab** [comment]
Please check the file paths in the params.txt file.
The paths for all files are based on the docker container in the "params.txt" file.

**Comment by yotsa** [comment]
> Please check the file paths in the params.txt file. The paths for all files are based on the docker container in the "params.txt" file.

did as you say and put the /rbrc_wd/reference or /rbrc_wd/read in params.txt, the command now is 

docker run --rm=True -v /RUN/reference:/rbrc_wd/reference -v /RUN/read:/rbrc_wd/read/ -v /RUN/output:/rbrc_wd/output -t jkimlab/rbrc:latest RBRC.pl -p /rbrc_wd/output/params.txt -o /rbrc_wd/output

where /RUN/read is my actual local disk path. still got the same error.

**Comment by jkimlab** [comment]
Please write the file path inside the params.txt file referring to the following.

```
# FASTQ
>LIB1
/rbrc_wd/read/fastq_1.fq
/rbrc_wd/read/fastq_2.fq
```

**Comment by yotsa** [comment]
Still not working. Below is the params.txt: 

 #---------------------------------------------------------------------------------------#
 ## Mendatory !
 # Reference genomes
 REF    1       OK5     /rbrc_wd/reference/XXX1_OK5.fa
 REF    2       KON     /rbrc_wd/reference/XXX2_KON.fa

 # NGS reads
 # FASTQ
 >LIB1
 /rbrc_wd/read/XXX106_trimmed_1.fastq
 /rbrc_wd/read/XXX106_trimmed_2.fastq

 #---------------------------------------------------------------------------------------#
 ## Optional
 # Running paramters
 THREADS        96
 REF_SIMILARITY_CUTOFF  80
 MAPQ   10

 # Pairwise alignment & synteny block construction params
 RESOLUTION     10000

 # Physical coverage paramters
 PHY_CUTOFF     LIB1    5

 # Distance based clustering paramters
 DBC_READ_DIST_CUTOFF   1000

 # Cluster merging parameter
 MERGE_MIN_READS        5
 #---------------------------------------------------------------------------------------#

**Comment by jkimlab** [comment]
Is the "params.txt" file located inside the /RUN/output directory?
The error occurs when the "params.txt" file cannot be read.

**Comment by yotsa** [comment]
yes, the params.txt file is in the /RUN/output directory. 

was the path to params.txt file after -p option supposed to be real path (my '/RUN/output/params.txt') or the path for docker ('/rbrc_wd/output/params.txt')?

**Comment by jkimlab** [comment]
> was the path to params.txt file after -p option supposed to be real path (my '/RUN/output/params.txt') or the path for docker ('/rbrc_wd/output/params.txt')?

/rbrc_wd/output/params.txt is right. 
Since the error does not occur for me, I cannot accurately determine what the problem is.
Would you like to check the permissions of the params.txt file?
my params.txt file has set "644".

**Comment by gabelow** [comment]
Hi,

Thanks for this program. I ran into pretty much the same error as the others and tried to do more investigation. This was the error produced in OUTPUTDIR/SynBased_clustering/synteny_blocks/log:

- reading OUTPUTDIR/chainNet/xxxXxx/aaaAaa/net/seq97.net
- reading OUTPUTDIR/chainNet/xxxXxx/bbbBbb/net/seq97.net
- reading OUTPUTDIR/chainNet/xxxXxx/cccCcc/net/seq97.net
- processing aaaAaa.raw.segs
make: *** [Grab.Data] Segmentation fault

I noticed that the .net files it was trying to read were empty, and that it didn't seem to be reading all the available files in the net directory defined in OUTPUTDIR/SynBased_clustering/synteny_blocks/config.file. When I concatenated all .net files in that folder into a new file and moved the rest away, the program was able to correctly read the .net data and move onto past that step. 

Unfortunately, now I have a problem resuming the run. Is it possible to resume the run from this point onwards? When I try to make the program call again, it attempts to do everything again from scratch - which I guess will end up with the same errors because the .net files will be remade and will need to be concatenated again.

Your help would be greatly appreciated.

Cheers,
Gabriel

**Comment by mia110214** [comment]
Hello, thank you for your interest. Currently, there is no option to start from the middle, and when executed, a new file is automatically created, so it is not possible to execute with an arbitrary file.
I recommend trying a resolution of 1000.
